// Mocks generated by Mockito 5.4.6 from annotations
// in dash/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i5;
import 'dart:io' as _i7;

import 'package:cloud_firestore/cloud_firestore.dart' as _i3;
import 'package:dash/models/badge_model.dart' as _i16;
import 'package:dash/services/auth_service.dart' as _i4;
import 'package:dash/services/badge_service.dart' as _i15;
import 'package:dash/services/favorite_route_repository.dart' as _i12;
import 'package:dash/services/follow_service.dart' as _i14;
import 'package:dash/services/profile_service.dart' as _i6;
import 'package:dash/services/push_notification_service.dart' as _i8;
import 'package:dash/services/route_repository.dart' as _i9;
import 'package:dash/services/run_session_repository.dart' as _i13;
import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:latlong2/latlong.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserCredential_0 extends _i1.SmartFake
    implements _i2.UserCredential {
  _FakeUserCredential_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentSnapshot_1<T extends Object?> extends _i1.SmartFake
    implements _i3.DocumentSnapshot<T> {
  _FakeDocumentSnapshot_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserMetadata_2 extends _i1.SmartFake implements _i2.UserMetadata {
  _FakeUserMetadata_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMultiFactor_3 extends _i1.SmartFake implements _i2.MultiFactor {
  _FakeMultiFactor_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIdTokenResult_4 extends _i1.SmartFake implements _i2.IdTokenResult {
  _FakeIdTokenResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfirmationResult_5 extends _i1.SmartFake
    implements _i2.ConfirmationResult {
  _FakeConfirmationResult_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_6 extends _i1.SmartFake implements _i2.User {
  _FakeUser_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i2.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i5.Stream<_i2.User?>.empty(),
          )
          as _i5.Stream<_i2.User?>);

  @override
  _i5.Future<_i2.UserCredential> registerWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerWithEmail, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#registerWithEmail, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<_i2.UserCredential> loginWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithEmail, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#loginWithEmail, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<_i2.UserCredential?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i5.Future<_i2.UserCredential?>.value(),
          )
          as _i5.Future<_i2.UserCredential?>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> resendVerificationEmail() =>
      (super.noSuchMethod(
            Invocation.method(#resendVerificationEmail, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileService extends _i1.Mock implements _i6.ProfileService {
  MockProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.DocumentSnapshot<Map<String, dynamic>>> getProfileDoc() =>
      (super.noSuchMethod(
            Invocation.method(#getProfileDoc, []),
            returnValue:
                _i5.Future<_i3.DocumentSnapshot<Map<String, dynamic>>>.value(
                  _FakeDocumentSnapshot_1<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getProfileDoc, []),
                  ),
                ),
          )
          as _i5.Future<_i3.DocumentSnapshot<Map<String, dynamic>>>);

  @override
  _i5.Future<String?> fetchUsername(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUsername, [uid]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<bool> isProfileComplete() =>
      (super.noSuchMethod(
            Invocation.method(#isProfileComplete, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> createProfile({
    required String? username,
    required String? name,
    required String? surname,
    required String? bio,
    _i7.File? profileImage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createProfile, [], {
              #username: username,
              #name: name,
              #surname: surname,
              #bio: bio,
              #profileImage: profileImage,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveNickname(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#saveNickname, [username]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> isUsernameTaken(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#isUsernameTaken, [username]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [PushNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPushNotificationService extends _i1.Mock
    implements _i8.PushNotificationService {
  MockPushNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [RouteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouteRepository extends _i1.Mock implements _i9.RouteRepository {
  MockRouteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> publishRoute({
    required String? name,
    required List<_i10.LatLng>? waypoints,
    required List<_i10.LatLng>? routePolyline,
    required double? distanceMeters,
    required double? estimatedTimeMin,
    required double? estimatedCalories,
    required bool? isLoop,
    required double? loopAreaM2,
    bool? isPublic = false,
    String? sourceSessionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#publishRoute, [], {
              #name: name,
              #waypoints: waypoints,
              #routePolyline: routePolyline,
              #distanceMeters: distanceMeters,
              #estimatedTimeMin: estimatedTimeMin,
              #estimatedCalories: estimatedCalories,
              #isLoop: isLoop,
              #loopAreaM2: loopAreaM2,
              #isPublic: isPublic,
              #sourceSessionId: sourceSessionId,
            }),
            returnValue: _i5.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#publishRoute, [], {
                  #name: name,
                  #waypoints: waypoints,
                  #routePolyline: routePolyline,
                  #distanceMeters: distanceMeters,
                  #estimatedTimeMin: estimatedTimeMin,
                  #estimatedCalories: estimatedCalories,
                  #isLoop: isLoop,
                  #loopAreaM2: loopAreaM2,
                  #isPublic: isPublic,
                  #sourceSessionId: sourceSessionId,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<List<_i9.SavedRoute>> fetchUserRoutes() =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserRoutes, []),
            returnValue: _i5.Future<List<_i9.SavedRoute>>.value(
              <_i9.SavedRoute>[],
            ),
          )
          as _i5.Future<List<_i9.SavedRoute>>);

  @override
  _i5.Future<List<_i9.SavedRoute>> fetchRoutesForUser(
    String? userId, {
    bool? publicOnly = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchRoutesForUser,
              [userId],
              {#publicOnly: publicOnly},
            ),
            returnValue: _i5.Future<List<_i9.SavedRoute>>.value(
              <_i9.SavedRoute>[],
            ),
          )
          as _i5.Future<List<_i9.SavedRoute>>);

  @override
  _i5.Future<void> renameRoute(String? id, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#renameRoute, [id, name]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void invalidateCache() => super.noSuchMethod(
    Invocation.method(#invalidateCache, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> deleteRoute(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRoute, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [FavoriteRouteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteRouteRepository extends _i1.Mock
    implements _i12.FavoriteRouteRepository {
  MockFavoriteRouteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> isFavorited(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorited, [sessionId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> favoriteSession(
    String? sessionId, {
    required String? routeName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #favoriteSession,
              [sessionId],
              {#routeName: routeName},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> unfavoriteRoute(String? routeId) =>
      (super.noSuchMethod(
            Invocation.method(#unfavoriteRoute, [routeId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> renameFavorite(String? routeId, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#renameFavorite, [routeId, name]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.SavedRoute>> fetchFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#fetchFavorites, []),
            returnValue: _i5.Future<List<_i9.SavedRoute>>.value(
              <_i9.SavedRoute>[],
            ),
          )
          as _i5.Future<List<_i9.SavedRoute>>);

  @override
  void invalidateCache() => super.noSuchMethod(
    Invocation.method(#invalidateCache, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [RunSessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRunSessionRepository extends _i1.Mock
    implements _i13.RunSessionRepository {
  MockRunSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> saveSession({
    required String? name,
    required double? distanceMeters,
    required Duration? duration,
    required double? avgPaceMinPerKm,
    double? maxPaceMinPerKm,
    required double? elevationDifferenceMeters,
    required int? loopsCompleted,
    required List<_i10.LatLng>? path,
    required List<List<_i10.LatLng>>? closedLoops,
    int? avgHeartRateBpm,
    int? maxHeartRateBpm,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveSession, [], {
              #name: name,
              #distanceMeters: distanceMeters,
              #duration: duration,
              #avgPaceMinPerKm: avgPaceMinPerKm,
              #maxPaceMinPerKm: maxPaceMinPerKm,
              #elevationDifferenceMeters: elevationDifferenceMeters,
              #loopsCompleted: loopsCompleted,
              #path: path,
              #closedLoops: closedLoops,
              #avgHeartRateBpm: avgHeartRateBpm,
              #maxHeartRateBpm: maxHeartRateBpm,
            }),
            returnValue: _i5.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#saveSession, [], {
                  #name: name,
                  #distanceMeters: distanceMeters,
                  #duration: duration,
                  #avgPaceMinPerKm: avgPaceMinPerKm,
                  #maxPaceMinPerKm: maxPaceMinPerKm,
                  #elevationDifferenceMeters: elevationDifferenceMeters,
                  #loopsCompleted: loopsCompleted,
                  #path: path,
                  #closedLoops: closedLoops,
                  #avgHeartRateBpm: avgHeartRateBpm,
                  #maxHeartRateBpm: maxHeartRateBpm,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i13.RunPrivateMetrics?> fetchPrivateMetrics(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPrivateMetrics, [sessionId]),
            returnValue: _i5.Future<_i13.RunPrivateMetrics?>.value(),
          )
          as _i5.Future<_i13.RunPrivateMetrics?>);

  @override
  _i5.Future<List<_i13.RunSession>> fetchUserSessions({String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserSessions, [], {#userId: userId}),
            returnValue: _i5.Future<List<_i13.RunSession>>.value(
              <_i13.RunSession>[],
            ),
          )
          as _i5.Future<List<_i13.RunSession>>);

  @override
  _i5.Future<_i13.RunSession?> fetchSessionById(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSessionById, [sessionId]),
            returnValue: _i5.Future<_i13.RunSession?>.value(),
          )
          as _i5.Future<_i13.RunSession?>);
}

/// A class which mocks [FollowService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFollowService extends _i1.Mock implements _i14.FollowService {
  MockFollowService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> toggleFollow({
    required String? currentUserId,
    required String? targetUserId,
    required bool? isCurrentlyFollowing,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFollow, [], {
              #currentUserId: currentUserId,
              #targetUserId: targetUserId,
              #isCurrentlyFollowing: isCurrentlyFollowing,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [BadgeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBadgeService extends _i1.Mock implements _i15.BadgeService {
  MockBadgeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i16.BadgeModel>> getAllBadges(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getAllBadges, [userId]),
            returnValue: _i5.Future<List<_i16.BadgeModel>>.value(
              <_i16.BadgeModel>[],
            ),
          )
          as _i5.Future<List<_i16.BadgeModel>>);

  @override
  _i5.Future<List<_i16.BadgeModel>> getHomeBadges(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getHomeBadges, [userId]),
            returnValue: _i5.Future<List<_i16.BadgeModel>>.value(
              <_i16.BadgeModel>[],
            ),
          )
          as _i5.Future<List<_i16.BadgeModel>>);

  @override
  _i5.Future<List<_i16.BadgeModel>> getProfileBadges(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileBadges, [userId]),
            returnValue: _i5.Future<List<_i16.BadgeModel>>.value(
              <_i16.BadgeModel>[],
            ),
          )
          as _i5.Future<List<_i16.BadgeModel>>);
}

/// A class which mocks [UserCredential].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserCredential extends _i1.Mock implements _i2.UserCredential {
  MockUserCredential() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i2.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get emailVerified =>
      (super.noSuchMethod(Invocation.getter(#emailVerified), returnValue: false)
          as bool);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false)
          as bool);

  @override
  _i2.UserMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeUserMetadata_2(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i2.UserMetadata);

  @override
  List<_i2.UserInfo> get providerData =>
      (super.noSuchMethod(
            Invocation.getter(#providerData),
            returnValue: <_i2.UserInfo>[],
          )
          as List<_i2.UserInfo>);

  @override
  String get uid =>
      (super.noSuchMethod(
            Invocation.getter(#uid),
            returnValue: _i11.dummyValue<String>(this, Invocation.getter(#uid)),
          )
          as String);

  @override
  _i2.MultiFactor get multiFactor =>
      (super.noSuchMethod(
            Invocation.getter(#multiFactor),
            returnValue: _FakeMultiFactor_3(
              this,
              Invocation.getter(#multiFactor),
            ),
          )
          as _i2.MultiFactor);

  @override
  _i5.Future<void> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getIdToken([bool? forceRefresh = false]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdToken, [forceRefresh]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<_i2.IdTokenResult> getIdTokenResult([
    bool? forceRefresh = false,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdTokenResult, [forceRefresh]),
            returnValue: _i5.Future<_i2.IdTokenResult>.value(
              _FakeIdTokenResult_4(
                this,
                Invocation.method(#getIdTokenResult, [forceRefresh]),
              ),
            ),
          )
          as _i5.Future<_i2.IdTokenResult>);

  @override
  _i5.Future<_i2.UserCredential> linkWithCredential(
    _i2.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithCredential, [credential]),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#linkWithCredential, [credential]),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<_i2.UserCredential> linkWithProvider(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithProvider, [provider]),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#linkWithProvider, [provider]),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<_i2.UserCredential> reauthenticateWithProvider(
    _i2.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithProvider, [provider]),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#reauthenticateWithProvider, [provider]),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<_i2.UserCredential> reauthenticateWithPopup(
    _i2.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithPopup, [provider]),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#reauthenticateWithPopup, [provider]),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<void> reauthenticateWithRedirect(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithRedirect, [provider]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.UserCredential> linkWithPopup(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPopup, [provider]),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#linkWithPopup, [provider]),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<void> linkWithRedirect(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithRedirect, [provider]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.ConfirmationResult> linkWithPhoneNumber(
    String? phoneNumber, [
    _i2.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i5.Future<_i2.ConfirmationResult>.value(
              _FakeConfirmationResult_5(
                this,
                Invocation.method(#linkWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.ConfirmationResult>);

  @override
  _i5.Future<_i2.UserCredential> reauthenticateWithCredential(
    _i2.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithCredential, [credential]),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#reauthenticateWithCredential, [credential]),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> sendEmailVerification([
    _i2.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, [actionCodeSettings]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.User> unlink(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#unlink, [providerId]),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_6(this, Invocation.method(#unlink, [providerId])),
            ),
          )
          as _i5.Future<_i2.User>);

  @override
  _i5.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updatePhoneNumber(
    _i2.PhoneAuthCredential? phoneCredential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhoneNumber, [phoneCredential]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#updateDisplayName, [displayName]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updatePhotoURL(String? photoURL) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhotoURL, [photoURL]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateProfile({String? displayName, String? photoURL}) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #photoURL: photoURL,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> verifyBeforeUpdateEmail(
    String? newEmail, [
    _i2.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#verifyBeforeUpdateEmail, [
              newEmail,
              actionCodeSettings,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
